### ISSUE TITLE
Cloudflare adapter and Esbuild fails despite using both the nodejs_compat and nodejs_compact flags

### ISSUE THREAD

**Issue by capndave** [withastro/adapters#106]
### Astro Info

```block
Astro                    v4.0.6
Node                     v18.16.0
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             none
```

### Describe the Bug

I have set up a project to deploy to Cloudflare when GitHub is updated, using [this Cloudflare tutorial](https://developers.cloudflare.com/pages/framework-guides/deploy-an-astro-site/) as my template. On commit to my repo, a build runs with esbuild and node-related failures, as shown below. I have added both the `nodejs_compat` and `nodejs_compact` flags in my cloudflare project settings.

```bash
7:22:34.835	23:22:34 [build] Rearranging server assets...
17:22:34.866	✘ [ERROR] Could not resolve "os"
17:22:34.867	
17:22:34.867	    node_modules/svgo/lib/svgo-node.js:3:19:
17:22:34.867	      3 │ const os = require('os');
17:22:34.868	        ╵                    ~~~~
17:22:34.868	
17:22:34.868	  The package "os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
17:22:34.868	
17:22:34.868	✘ [ERROR] Could not resolve "fs"
17:22:34.868	
17:22:34.868	    node_modules/svgo/lib/svgo-node.js:4:19:
17:22:34.869	      4 │ const fs = require('fs');
17:22:34.869	        ╵                    ~~~~
17:22:34.869	
17:22:34.869	  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
17:22:34.869	
17:22:34.869	✘ [ERROR] Could not resolve "url"
17:22:34.871	
17:22:34.871	    node_modules/svgo/lib/svgo-node.js:5:34:
17:22:34.871	      5 │ const { pathToFileURL } = require('url');
17:22:34.871	        ╵                                   ~~~~~
17:22:34.871	
17:22:34.872	  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
17:22:34.872	
17:22:34.872	✘ [ERROR] Could not resolve "path"
17:22:34.872	
17:22:34.872	    node_modules/svgo/lib/svgo-node.js:6:21:
17:22:34.872	      6 │ const path = require('path');
17:22:34.872	        │                      ~~~~~~
17:22:34.873	        ╵                      "./path"
17:22:34.873	
17:22:34.873	  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
17:22:34.873	
17:22:35.227	Could not resolve "os"
17:22:35.227	  Stack trace:
17:22:35.227	    at failureErrorWithLog (/opt/buildhome/repo/node_modules/esbuild/lib/main.js:1650:15)
17:22:35.228	    at /opt/buildhome/repo/node_modules/esbuild/lib/main.js:1003:52
17:22:35.228	    at /opt/buildhome/repo/node_modules/esbuild/lib/main.js:1085:16
17:22:35.228	    at handleIncomingPacket (/opt/buildhome/repo/node_modules/esbuild/lib/main.js:763:9)
17:22:35.228	    at Socket.emit (node:events:514:28)
17:22:35.258	Failed: Error while executing user command. Exited with error code: 1
17:22:35.268	Failed: build command exited with code: 1
17:22:36.277	Failed: error occurred while running build command
```

### What's the expected result?

A successful build

### Link to Minimal Reproducible Example

https://github.com/capndave/lilnonnas-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
@capndave Thank you for your example. What you are trying to solve is not possible. Cloudflare Pages do not support node imports without the prefix `node:*`

**Comment by capndave** [comment]
@alexanderniebuhr what do you mean by "path the adapter"?

**Comment by alexanderniebuhr** [comment]
> Is there somewhere in my code or in the Cloudflare console that I need to add node:*? What needs to be prefixed, or where can I add the prefix?

It looks like the imports come from `svgo`, so it would need to be changed in that

>  "path the adapter"?

I meant to say `patch the adapter`, using `pnpm patch` or `patch-package`

**Comment by capndave** [comment]
Thanks you two! For anyone who lands here with a similar issue, the problem came from using astro-icon. See [here](https://github.com/natemoo-re/astro-icon/issues/35) for an explanation of how to patch for this particular issue.
