### ISSUE TITLE
Cloudflare build failed

### ISSUE THREAD

**Issue by shriharip** [withastro/adapters#112]
### Astro Info

```block
Astro                    v4.0.2
Node                     v18.18.2
System                   macOS (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
```

### Describe the Bug

Build fails  when generating server side assets. Astro set for ssr rendering.
```
10:01:32.919	 finalizing server assets 
10:01:32.919	
10:01:32.919	09:01:32 [build] Rearranging server assets...
10:01:33.000	✘ [ERROR] Could not resolve "events"
10:01:33.001	
10:01:33.001	    node_modules/.pnpm/node-cache@5.1.2/node_modules/node-cache/lib/node_cache.js:18:25:
10:01:33.001	      18 │   EventEmitter = require('events').EventEmitter;
10:01:33.002	         ╵                          ~~~~~~~~
10:01:33.002	
10:01:33.002	  The package "events" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
10:01:33.002	
10:01:33.116	✘ [ERROR] Could not resolve "os"
10:01:33.116	
10:01:33.116	    dist/$server_build/chunks/pages/index_Zh0V2mBm.mjs:1:25:
10:01:33.116	      1 │ import require$$0$4 from 'os';
10:01:33.117	        ╵                          ~~~~
10:01:33.117	
10:01:33.117	  The package "os" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
10:01:33.117	
10:01:33.131	✘ [ERROR] Could not resolve "fs"
10:01:33.132	
10:01:33.132	    dist/$server_build/chunks/pages/index_Zh0V2mBm.mjs:2:7:
10:01:33.132	      2 │ import 'fs';
10:01:33.132	        ╵        ~~~~
10:01:33.132	
10:01:33.133	  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
10:01:33.133	
10:01:33.138	✘ [ERROR] Could not resolve "url"
10:01:33.138	
10:01:33.139	    dist/$server_build/chunks/pages/index_Zh0V2mBm.mjs:3:7:
10:01:33.139	      3 │ import 'url';
10:01:33.139	        ╵        ~~~~~
10:01:33.139	
10:01:33.139	  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
10:01:33.139	
10:01:33.140	✘ [ERROR] Could not resolve "path"
10:01:33.140	
10:01:33.140	    dist/$server_build/chunks/pages/index_Zh0V2mBm.mjs:4:7:
10:01:33.140	      4 │ import 'path';
10:01:33.140	        ╵        ~~~~~~
10:01:33.140	
10:01:33.140	  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
10:01:33.141	
10:01:33.602	Could not resolve "os"
10:01:33.603	  Stack trace:
10:01:33.603	    at failureErrorWithLog (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.7/node_modules/esbuild/lib/main.js:1650:15)
10:01:33.603	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.7/node_modules/esbuild/lib/main.js:1003:52
10:01:33.603	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.7/node_modules/esbuild/lib/main.js:1085:16
10:01:33.604	    at handleIncomingPacket (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.7/node_modules/esbuild/lib/main.js:763:9)
10:01:33.604	    at Socket.emit (node:events:514:28)
10:01:33.604	    at readableAddChunk (node:internal/streams/readable:297:9)
10:01:33.604	    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
10:01:33.637	npm notice 
10:01:33.638	npm notice New major version of npm available! 9.6.7 -> 10.2.5
10:01:33.638	npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
10:01:33.638	npm notice Run `npm install -g npm@10.2.5` to update!
10:01:33.639	npm notice 
10:01:33.649	Failed: Error while executing user command. Exited with error code: 1
10:01:33.658	Failed: build command exited with code: 1
10:01:34.623	Failed: error occurred while running build command
```

### What's the expected result?

Build should not failed.

### Link to Minimal Reproducible Example

ca

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by shriharip** [comment]
It might be because of the non ESM modules in my server side code.? That's what I understood. If my understanding is correct, plz close this issue.

**Comment by ematipico** [comment]
@shriharip you should provide a reproduction to help you. 

By the way, Cloudflare has **limited** support for Node.js modules: https://github.com/withastro/adapters/tree/main/packages/cloudflare#nodejs-compatibility

You must use the `node:*` protocol and can use only the modules listed int he documentation. If you need other modules, you can't use the Cloudflare adapter.

**Comment by alexanderniebuhr** [comment]
As @ematipico said, we would need a reproduction, but peeking at the error, it looks like the `node-cache` package, does add to the list.

**Comment by shriharip** [comment]
@ematipico @alexanderniebuhr thanks for your response. Since it is a private repo, I can provide access to the repo. Really need to get this working. As I do not want to change the deploy from Cloudflare.

**Comment by ematipico** [comment]
@shriharip you'll have to create a minimal repository. Also, did you change your imports by using `node:*`?

**Comment by alexanderniebuhr** [comment]
@shriharip I can't access it. Please look at the error message and see what other packages might be causing it. `node-cache` was one, but there might be more

**Comment by alexanderniebuhr** [comment]
I have another idea, it also could be cause by `astro:assets`, but again as @ematipico already said, we need to have a **minimal** reproduction to really help you

**Comment by shriharip** [comment]
@alexanderniebuhr @ematipico . 
I now have the Repo ready https://github.com/shriharip/astrocloudflare.git 
thanks

**Comment by alexanderniebuhr** [comment]
@shriharip Oh I'm pretty sure you are facing the same issue as https://github.com/withastro/adapters/issues/106
`svgo` is not currently not supported, and since it is an upstream package, we can't do anything to fix it.

You might have some luck with workarounds posted here: https://github.com/natemoo-re/astro-icon/issues/35#issuecomment-1578101502

**Comment by shriharip** [comment]
@alexanderniebuhr thanks so much. that workaround fixed the issue for now.
@ematipico @alexanderniebuhr  thanks so much
