### ISSUE TITLE
Netlify:`Astro.clientAddress` is not available

### ISSUE THREAD

**Issue by EddyVinck** [withastro/adapters#142]
### Astro Info

```block
Astro                    v4.2.6
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/netlify (latest version 5.0)
Integrations             @astrojs/mdx
                         @astrojs/sitemap
                         @astrojs/solid-js
                         @astrojs/tailwind
```

### Describe the Bug

I tried using the `clientAddress` but the logs say it isn't available in the Netlify adapter

```
12:40:40 AM: 🚨 Could not enable emoji reactions for "enabling-emoji-post-reactions. Reason:"
12:40:40 AM: ClientAddressNotAvailable: `Astro.clientAddress` is not available in the `@astrojs/netlify` adapter. File an issue with the adapter to add support.
12:40:40 AM:     at get clientAddress [as clientAddress] (file:///opt/build/repo/node_modules/astro/dist/core/render/result.js:119:21)
12:40:40 AM:     at file:///opt/build/repo/.netlify/functions-internal/ssr/chunks/prerender_llcG8PKz.mjs:341:12
12:40:40 AM:     at AstroComponentInstance.EmojiReactions [as factory] (file:///opt/build/repo/.netlify/functions-internal/ssr/chunks/astro_uODeDaI0.mjs:219:12)
12:40:40 AM:     at AstroComponentInstance.init (file:///opt/build/repo/.netlify/functions-internal/ssr/chunks/astro_uODeDaI0.mjs:1038:29)
12:40:40 AM:     at AstroComponentInstance.render (file:///opt/build/repo/.netlify/functions-internal/ssr/chunks/astro_uODeDaI0.mjs:1043:18)
12:40:40 AM:     at Object.render (file:///opt/build/repo/.netlify/functions-internal/ssr/chunks/astro_uODeDaI0.mjs:1507:22)
12:40:40 AM:     at renderChild (file:///opt/build/repo/.netlify/functions-internal/ssr/chunks/astro_uODeDaI0.mjs:994:17) {
12:40:40 AM:   loc: undefined,
12:40:40 AM:   title: "`Astro.clientAddress` is not available in current adapter.",
12:40:40 AM:   hint: undefined,
12:40:40 AM:   frame: undefined,
12:40:40 AM:   type: "AstroError"
12:40:40 AM: }
```

### What's the expected result?

I should be able to get the user's IP

### Link to Minimal Reproducible Example

Here you can see what I tried https://github.com/EddyVinck/astro-engineering-blog/commit/5827c40422748bd53fa27e5709c84f5bffada739

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ematipico** [comment]
cc @lilnasy

**Comment by EddyVinck** [comment]
False alarm, sorry about that

The error seems to be misleading 

https://github.com/withastro/docs/issues/4767#issuecomment-1914125100
