### ISSUE TITLE
Can't use experimental.actions with cloudflare adapter

### ISSUE THREAD

**Issue by yzn-h** [withastro/adapters#338]
### Astro Info

```block
Astro                    v4.12.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             none

(stackblitz)
```

### Describe the Bug

when i enable experimental.actions and using cloudflare adapter in `pnpm dev` everything works fine. but when I try to `pnpm build` I get this compile error
 ```
 12:38:01 [ERROR] [vite] x Build failed in 118ms
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "node:async_hooks" imported from "node_modules/.pnpm/astro@4.12.2_@types+node@20.14.12_typescript@5.5.4/node_modules/astro/dist/actions/runtime/store.js". Consider disabling ssr.noExternal or remove the built-in dependency.
  Stack trace:
    at getRollupError (file:///home/yzn/projects/b22/node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at Object.error (file:///home/yzn/projects/b22/node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:19623:20)
    at Object.handler (file:///home/yzn/projects/b22/node_modules/.pnpm/vite@5.3.4_@types+node@20.14.12/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:65950:15)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/yzn/projects/b22/node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:19708:28)
    at async ModuleLoader.resolveId (file:///home/yzn/projects/b22/node_modules/.pnpm/rollup@4.19.0/node_modules/rollup/dist/es/shared/node-entry.js:18792:15)
 ```

### What's the expected result?

to build without errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-uf8vjy?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexanderniebuhr** [comment]
You need to add the Node.js import to your astro configuration, we have it documented here: https://docs.astro.build/en/guides/integrations-guide/cloudflare/#nodejs-compatibility

**Comment by yzn-h** [comment]
@alexanderniebuhr
thank you adding
```js
  vite: {
    ssr: {
      external: ['node:async_hooks'],
    },
  },
```
to astro.config.mjs fixed the issue

would be nice if the error massage directed me to docs

**Comment by alexanderniebuhr** [comment]
I agree with that, but the error message is not managed by us, so I'm not sure if we can add a link to docs to it. If it's possible, we will add it.
