### ISSUE TITLE
`@astrojs/vercel` - AdapterSupportOutputMismatch

### ISSUE THREAD

**Issue by phenomen** [withastro/adapters#430]
### Astro Info

```block
Astro                    v5.0.0-beta.6
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/vercel
Integrations             none
```

### Describe the Bug

After upgrading to `"astro": "5.0.0-beta.6"` and `"@astrojs/vercel": "8.0.0-beta.3"` I get an error:

```
[AdapterSupportOutputMismatch] The `@astrojs/vercel` adapter is configured to output a static website, but the project contains server-rendered pages. Please install and configure the appropriate server adapter for your final deployment.
  Error reference:
    https://docs.astro.build/en/reference/errors/adapter-support-output-mismatch/
  Stack trace:
    at new AstroError (file:///home/projects/withastro-astro-fewhsc/node_modules/astro/dist/core/errors/errors.js:37:5)
    at setAdapter (file:///home/projects/withastro-astro-fewhsc/node_modules/astro/dist/integrations/hooks.js:265:45)
    at Module.runHookConfigDone (file:///home/projects/withastro-astro-fewhsc/node_modules/astro/dist/integrations/hooks.js:262:59)
    at async AstroBuilder.run (file:///home/projects/withastro-astro-fewhsc/node_modules/astro/dist/core/build/index.js:196:23)
    at async build (file:///home/projects/withastro-astro-fewhsc/node_modules/astro/dist/cli/build/index.js:44:3)
 ELIFECYCLE  Command failed with exit code 1.
```

From what I understand, `static` is a correct output if just a few pages/endpoints have `export const prerender = false;`

In the linked reproduction, run `npm run build` to repro the error.

### What's the expected result?

Successful build.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-fewhsc?file=package.json

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
Looks like we need to update the vercel adapter code here to use the value of `buildOutput` from the `astro:config:done` hook instead of from the `astro:config:setup` hook: https://github.com/withastro/adapters/blob/aed689d6af8f02cf059689f289b98881b5a4e335/packages/vercel/src/index.ts#L277-L289. That way `setAdapter` uses the right value that doesn't trigger the error.

That solves this issue, however it also looks like vercel is using the `buildOutput` during `astro:config:setup`, which is a little problematic because that's not the final value yet. https://github.com/withastro/adapters/blob/aed689d6af8f02cf059689f289b98881b5a4e335/packages/vercel/src/index.ts#L196-L207

Unless there's a way to share the same config in agnostic of server or static, @ematipico I think making `@astrojs/adapter` as a single entrypoint might not work here. Perhaps you have some ideas to fix this.

**Comment by ematipico** [comment]
> which is a little problematic because that's not the final value yet. 

Is there a case where `buildOutput` starts as `server` but then the final value is `static`?

**Comment by bluwy** [comment]
It should only ever go from `static` to `server` based on this code: https://github.com/withastro/astro/blob/731b69712b0e9c5d5a4058db3fa3e8bf628c7aad/packages/astro/src/core/routing/manifest/prerender.ts#L28

I've discussed with Erika before if we could detect the case where the user set `server` but every route is set to prerender true, in which it should ended up as `static`, but we didn't implement it as it doesn't make sense to do so in practice.

**Comment by princemuel** [comment]
I'm also experiencing this problem

**Comment by samparmenter** [comment]
Having the same issue here. Output set to static as almost the entire site is static bar a couple of /api routes but using the @astro/vercel adaptor I am seeing `The `@astrojs/vercel` adapter is configured to output a static website, but the project contains server-rendered pages. Please install and configure the appropriate server adapter for your final deployment.`

In the single api route I currently have I have `export default prerender = false;`
