### ISSUE TITLE
Cannot find module 'cloudflare:email'

### ISSUE THREAD

**Issue by scruffymongrel** [withastro/adapters#441]
### Astro Info

```block
Astro                    v4.16.12
Node                     v22.2.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
```

### Describe the Bug

I'm trying to `import { EmailMessage } from 'cloudflare:email'` in an Astro page.

Normally this kinda import would be used in Workers just fine, but Astro seems unable to do the magic...

When I request the page, I get the following stack trace:

```
Error: Failed to load url cloudflare:email (resolved id: cloudflare:email) in /REDACTED_PATH/src/pages/for/enterprise.astro. Does the file exist?
    at loadAndTransform (file:///REDACTED_PATH/node_modules/.pnpm/vite@5.4.11_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51920:17)
    at async instantiateModule (file:///REDACTED_PATH/node_modules/.pnpm/vite@5.4.11_@types+node@22.9.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52874:44)
```

I'm using the following `astro.config.js`:

```js
import { defineConfig } from 'astro/config'
import tailwind from '@astrojs/tailwind'

import cloudflare from '@astrojs/cloudflare'

export default defineConfig({
  adapter: cloudflare({
    imageService: 'passthrough',
    platformProxy: {
      enabled: true
    }
  }),
  integrations: [tailwind()],
  output: 'hybrid',
  vite: {
    ssr: {
      external: ['cloudflare:email']
    }
  }
})
```

### What's the expected result?

I would like for the page to render without error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-6doees

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I don't think this is meant to be supported in dev, but maybe @alexanderniebuhr has a better idea of this.

**Comment by bluwy** [comment]
Yeah I don't think Cloudflare provides local support for that. I wonder if it's worth providing a better error message when a cloudflare builtin is encountered, if not maybe we can close this.

**Comment by alexanderniebuhr** [comment]
As you can see in this table, `email bindings` are not support for local dev: https://developers.cloudflare.com/workers/testing/local-development/#supported-resource-bindings-in-different-environments

**Comment by scruffymongrel** [comment]
Aha, thanks for the link!

Does that mean I can expect `import { EmailMessage } from 'cloudflare:email'` to work in production?

**Comment by pthurmond-vmlyr** [comment]
So I am seeing this very same problem in Cloudflare in a branch build (not the main/production branch). I haven't tested on prod. But its the Cloudflare env. I can't even finish the build on Cloudflare. How do I fix that?
